# Generated by Django 5.2.1 on 2025-07-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal', models.FloatField()),
            ],
            options={
                'db_table': 'carrinho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('rgb', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personalizacao',
            fields=[
                ('pk', models.CompositePrimaryKey('id_produto', 'id_cor', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'personalizacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preco', models.FloatField()),
                ('quantidade', models.BigIntegerField()),
                ('categoria', models.TextField()),
                ('material', models.TextField()),
                ('cor_padrao', models.TextField()),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('comprimento', models.FloatField(blank=True, null=True)),
                ('largura', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoCarrinho',
            fields=[
                ('pk', models.CompositePrimaryKey('id_produto', 'id_carrinho', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'produto_carrinho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('frete', models.CharField(max_length=9)),
                ('valor_total', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
