# Generated by Django 5.2.1 on 2025-07-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False},
        ),
    ]
