# Generated by Django 5.2.3 on 2025-07-10 17:21
# pylint: skip-file

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrinho',
            table='carrinho',
        ),
        migrations.AlterModelTable(
            name='cor',
            table='cor',
        ),
        migrations.AlterModelTable(
            name='personalizacao',
            table='personalizacao',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
        migrations.AlterModelTable(
            name='produtocarrinho',
            table='produto_carrinho',
        ),
    ]
