# pylint: skip-file

# Generated by Django 5.2.3 on 2025-07-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='personalizacao',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='produtocarrinho',
            options={'managed': False},
        ),
    ]
